In [1]:
ls

 Volume in drive C is Windows
 Volume Serial Number is CCCC-8701

 Directory of C:\Users\RAPETI\Untitled Folder

23-07-2019  12:34    <DIR>          .
23-07-2019  12:34    <DIR>          ..
23-07-2019  12:34    <DIR>          .ipynb_checkpoints
23-07-2019  12:34                72 Untitled.ipynb
               1 File(s)             72 bytes
               3 Dir(s)  94,975,946,752 bytes free


* The most important object defined in NumPy is an N-dimensional array type called *ndarray*.

In [16]:
import numpy as n
a=n.array([1,2,3])
print(a)
b=n.array([[3,4],[5,6]])
print(b)
c=n.array([1, 2, 3,4,5], ndmin=2)
print(c)
d=n.array([1,2,3],dtype=complex)
e=n.array([1,2,3],dtype=int)
f=n.array([1,2,3],dtype=float)
print(d,e,f)


[1 2 3]
[[3 4]
 [5 6]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j] [1 2 3] [1. 2. 3.]


* csv-common seperative value
* head function returns first 5 records in data by default,if we specifies the value then it returns those records
* tail function returns last 5 records
* attribute(describing of data) will not have paranthasis but methods(work or functions) will have paranthasis 
* axis=0(for rows),axis=1(for columns) 

In [53]:
import pandas as pan
data=pan.DataFrame({'Name of':['Alex','Bob','Gary','James'],'Age':[5,8,10,6]})
print(data)

  Name of  Age
0    Alex    5
1     Bob    8
2    Gary   10
3   James    6


In [54]:
print(data.index) # gives index
print()
print(data.columns) #gives columns names
print()
print(data.shape) # specifies the dimensons
print()
print(data.head)
print()
print(data.head(2))
print()
print(data.tail)
print()
print(data.tail(2))
print()
print(data['Name of'])#gives the values in columns
print()
print(data['Age'])#gives the values in columns
print()
print(data.Age)#gives the values in columns
print()
print(data.Age==8)
print()
print(data[data.Age==8])
print()


RangeIndex(start=0, stop=4, step=1)

Index(['Name of', 'Age'], dtype='object')

(4, 2)

<bound method NDFrame.head of   Name of  Age
0    Alex    5
1     Bob    8
2    Gary   10
3   James    6>

  Name of  Age
0    Alex    5
1     Bob    8

<bound method NDFrame.tail of   Name of  Age
0    Alex    5
1     Bob    8
2    Gary   10
3   James    6>

  Name of  Age
2    Gary   10
3   James    6

0     Alex
1      Bob
2     Gary
3    James
Name: Name of, dtype: object

0     5
1     8
2    10
3     6
Name: Age, dtype: int64

0     5
1     8
2    10
3     6
Name: Age, dtype: int64

0    False
1     True
2    False
3    False
Name: Age, dtype: bool

  Name of  Age
1     Bob    8



In [66]:
print(data.drop('Name of',axis=1))
print()
print(data.rename(columns={'Age':'Age of'},inplace=True))
print(data)
print()
print(data.rename(columns={'Name of':'Name'},inplace=True))
print(data)

   Age of
0       5
1       8
2      10
3       6

None
  Name of  Age of
0    Alex       5
1     Bob       8
2    Gary      10
3   James       6

None
    Name  Age of
0   Alex       5
1    Bob       8
2   Gary      10
3  James       6


In [71]:
a=data.copy()
print(a)
print()
data.sort_values("Name",ascending=False)
print(data)
print()
print(data.Name.sort_values(ascending=False))
print()
print(data.reset_index(inplace=True))
print(data)

   index   Name  Age of
0      0   Alex       5
1      1    Bob       8
2      2   Gary      10
3      3  James       6

   index   Name  Age of
0      0   Alex       5
1      1    Bob       8
2      2   Gary      10
3      3  James       6

3    James
2     Gary
1      Bob
0     Alex
Name: Name, dtype: object

None
   level_0  index   Name  Age of
0        0      0   Alex       5
1        1      1    Bob       8
2        2      2   Gary      10
3        3      3  James       6


In [73]:
import pandas as pf
dd=pf.read_csv(r"C:\Users\RAPETI\Book2.csv")
dd

names  MARKS
0    AA     11
1    BB     13
2    CC     24
3    DD     14